version: '3.9'
services:

  #PHP Service
  app:
    container_name: phplaravelnginx
    build: .
    restart: always
    env_file: .env
    ports:
      - "80:80"
    networks:
      - backend

networks:
    backend:

volumes:
    mysql:
