name: CI

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    env:
      PHP_CS_FIXER_VERSION: v3.7.0
    strategy:
      matrix:
        php:
          - '8.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl,mbstring
          tools: php-cs-fixer:${{ env.PHP_CS_FIXER_VERSION }}
          coverage: none
      - name: Run PHP-CS-Fixer Fix, version ${{ env.PHP_CS_FIXER_VERSION }}
        run: php-cs-fixer fix --dry-run --diff --ansi
  
  build:
    runs-on: ${{ matrix.os }}
    name: PHP v${{ matrix.php }} with Mongo v${{ matrix.mongodb }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, php: 8.1, mongodb: '5.0', experimental: false }
    steps:
      - name: "Installing php"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl,mbstring,xdebug,mongodb
          coverage: xdebug
          tools: composer
      - name: Show PHP version
        run: php -v && composer -V
      - name: Show Docker version
        run: if [[ "$DEBUG" == "true" ]]; then docker version && env; fi
        env:
          DEBUG: ${{secrets.DEBUG}}
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run tests
        run: |
          ./vendor/bin/phpunit --coverage-clover coverage.xml