name: CI

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    env:
      PHP_CS_FIXER_VERSION: v3.7.0
    strategy:
      matrix:
        php:
          - '8.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl,mbstring
          tools: php-cs-fixer:${{ env.PHP_CS_FIXER_VERSION }}
          coverage: none
      - name: Run PHP-CS-Fixer Fix, version ${{ env.PHP_CS_FIXER_VERSION }}
        run: php-cs-fixer fix --dry-run --diff --ansi
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Installing php"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl,mbstring,xdebug,mongodb
          coverage: xdebug
          tools: composer
      - name: Show PHP version
        run: php -v && composer -V
      - name: Show Docker version
        run: if [[ "$DEBUG" == "true" ]]; then docker version && env; fi
        env:
          DEBUG: ${{secrets.DEBUG}}
      - name: Download Composer cache dependencies from cache
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.os }}-composer-
      - name: Install dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run tests
        run: |
          ./vendor/bin/phpunit --coverage-clover coverage.xml