name: CI/CD

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    env:
      PHP_CS_FIXER_VERSION: v3.7.0
    strategy:
      matrix:
        php:
          - '8.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
        php-version: ${{ matrix.php }}
        extensions: curl,mbstring
        tools: php-cs-fixer:${{ env.PHP_CS_FIXER_VERSION }}
        coverage: none
      - name: Run PHP-CS-Fixer Fix, version ${{ env.PHP_CS_FIXER_VERSION }}
        run: php-cs-fixer fix --dry-run --diff --ansi
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate